In [38]:
# numpy

import numpy as np

In [39]:
np.array

<function numpy.array>

In [40]:
li =[10, 20, 30]
np.array(li)

array([10, 20, 30])

In [41]:
li2 = [[1,2,3], [10,20,30], [100,200,300]]
np.array(li2)

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

In [42]:
np.shape(li2)

(3, 3)

In [48]:
li3 = np.array([1,2,3,4,5])
li3.dtype

dtype('int64')

In [49]:
li3.shape

(5,)

In [51]:
li4 = np.array([[1,2,3,4,5], [4,5,6,7,8]])

In [52]:
li4.shape

(2, 5)

In [54]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
np.zeros((5,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [60]:
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [61]:
np.random.rand(3,5)

array([[0.08561345, 0.72406972, 0.92970774, 0.93709953, 0.2683991 ],
       [0.85393674, 0.23359817, 0.01870604, 0.88532384, 0.18150984],
       [0.55724347, 0.54881087, 0.82144579, 0.42742667, 0.62043561]])

In [62]:
np.random.randn(3,5)

array([[ 1.48899022,  0.6061522 ,  1.21334557, -0.15501276,  0.27297187],
       [-0.35308032, -1.28450502,  0.076253  ,  0.89989112,  0.11699092],
       [-0.39939294, -0.68325031, -0.96460647, -0.61089689,  0.96886015]])

In [65]:
np.random.randint(3,10, 4)

array([4, 3, 8, 8])

In [70]:
# pandas 1

import pandas as pd

series = pd.Series([10,20,30]) # similar to array but with indices
series

0    10
1    20
2    30
dtype: int64

In [71]:
series.index

RangeIndex(start=0, stop=3, step=1)

In [72]:
series.values

array([10, 20, 30])

In [73]:
ser1 = pd.Series([10,20,30], ["a", "b", "c"])

In [74]:
ser1

a    10
b    20
c    30
dtype: int64

In [76]:
data = {"a": 1, "b": 33, "c": 9}
ser2 = pd.Series(data)
ser2

a     1
b    33
c     9
dtype: int64

In [77]:
ser3 = pd.Series(["India", "Karnataka", "Bangalore"], index=["country", "state", "city"])

In [79]:
ser3

country        India
state      Karnataka
city       Bangalore
dtype: object

In [78]:
ser3["state"]

'Karnataka'

In [83]:
# dataframe

df = pd.DataFrame([[1,2,4], [5,6,7], [9,0,2]])
df

0  1  2
0  1  2  4
1  5  6  7
2  9  0  2

In [85]:
df2 = pd.DataFrame([[1,2,3], [4,5,6], [7,8,9], [10,11,12]], index=["a", "b", "c", "d"], columns=["x", "y", "z"])

In [86]:
df2

x   y   z
a   1   2   3
b   4   5   6
c   7   8   9
d  10  11  12

In [68]:
#pandas 2

weather_df = pd.read_csv("data/weather_2012.csv")

In [87]:
weather_df.describe()

Temp (C)  Dew Point Temp (C)  Rel Hum (%)  Wind Spd (km/h)  \
count  8784.000000         8784.000000  8784.000000      8784.000000   
mean      8.798144            2.555294    67.431694        14.945469   
std      11.687883           10.883072    16.918881         8.688696   
min     -23.300000          -28.500000    18.000000         0.000000   
25%       0.100000           -5.900000    56.000000         9.000000   
50%       9.300000            3.300000    68.000000        13.000000   
75%      18.800000           11.800000    81.000000        20.000000   
max      33.000000           24.400000   100.000000        83.000000   

       Visibility (km)  Stn Press (kPa)  
count      8784.000000      8784.000000  
mean         27.664447       101.051623  
std          12.622688         0.844005  
min           0.200000        97.520000  
25%          24.100000       100.560000  
50%          25.000000       101.070000  
75%          25.000000       101.590000  
max          48.300000       103.650000

In [88]:
weather_df.index

RangeIndex(start=0, stop=8784, step=1)

In [89]:
weather_df.shape

(8784, 8)

In [92]:
weather_df["Date/Time"] = pd.to_datetime(weather_df["Date/Time"]) # convert obj to datetime

In [93]:
weather_df["Date/Time"]

0      2012-01-01 00:00:00
1      2012-01-01 01:00:00
2      2012-01-01 02:00:00
3      2012-01-01 03:00:00
4      2012-01-01 04:00:00
               ...        
8779   2012-12-31 19:00:00
8780   2012-12-31 20:00:00
8781   2012-12-31 21:00:00
8782   2012-12-31 22:00:00
8783   2012-12-31 23:00:00
Name: Date/Time, Length: 8784, dtype: datetime64[ns]

In [95]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8784 entries, 0 to 8783
Data columns (total 8 columns):
 #   Column              Non-Null Count  Dtype         
---  ------              --------------  -----         
 0   Date/Time           8784 non-null   datetime64[ns]
 1   Temp (C)            8784 non-null   float64       
 2   Dew Point Temp (C)  8784 non-null   float64       
 3   Rel Hum (%)         8784 non-null   int64         
 4   Wind Spd (km/h)     8784 non-null   int64         
 5   Visibility (km)     8784 non-null   float64       
 6   Stn Press (kPa)     8784 non-null   float64       
 7   Weather             8784 non-null   object        
dtypes: datetime64[ns](1), float64(4), int64(2), object(1)
memory usage: 549.1+ KB


In [96]:
weather_df.tail()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa) Weather  
8779               30              9.7           100.13    Snow  
8780               24              9.7           100.03    Snow  
8781               28              4.8            99.95    Snow  
8782               28              9.7            99.91    Snow  
8783               30             11.3            99.89    Snow

In [97]:
weather_df["Wind Spd (km/h)"].unique()

array([ 4,  7,  6,  9, 15, 13, 20, 22, 19, 24, 30, 35, 39, 32, 33, 26, 44,
       43, 48, 37, 28, 17, 11,  0, 83, 70, 57, 46, 41, 52, 50, 63, 54,  2])

In [99]:
weather_df["Weather"].nunique() # num of unique vals

50

In [101]:
weather_df["Weather"].value_counts() # count of each value

Weather
Mainly Clear                               2106
Mostly Cloudy                              2069
Cloudy                                     1728
Clear                                      1326
Snow                                        390
Rain                                        306
Rain Showers                                188
Fog                                         150
Rain,Fog                                    116
Drizzle,Fog                                  80
Snow Showers                                 60
Drizzle                                      41
Snow,Fog                                     37
Snow,Blowing Snow                            19
Rain,Snow                                    18
Thunderstorms,Rain Showers                   16
Haze                                         16
Drizzle,Snow,Fog                             15
Freezing Rain                                14
Freezing Drizzle,Snow                        11
Freezing Drizzle                

In [105]:
len(weather_df[weather_df["Weather"] == "Clear"]["Weather"])

1326

In [109]:
len(weather_df[weather_df["Wind Spd (km/h)"] == 4])

474

In [4]:
weather_df

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0     2012-01-01 00:00:00      -1.8                -3.9           86   
1     2012-01-01 01:00:00      -1.8                -3.7           87   
2     2012-01-01 02:00:00      -1.8                -3.4           89   
3     2012-01-01 03:00:00      -1.5                -3.2           88   
4     2012-01-01 04:00:00      -1.5                -3.3           88   
...                   ...       ...                 ...          ...   
8779  2012-12-31 19:00:00       0.1                -2.7           81   
8780  2012-12-31 20:00:00       0.2                -2.4           83   
8781  2012-12-31 21:00:00      -0.5                -1.5           93   
8782  2012-12-31 22:00:00      -0.2                -1.8           89   
8783  2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24                   Fog  
1                   4              8.0           101.24                   Fog  
2                   7              4.0           101.26  Freezing Drizzle,Fog  
3                   6              4.0           101.27  Freezing Drizzle,Fog  
4                   7              4.8           101.23                   Fog  
...               ...              ...              ...                   ...  
8779               30              9.7           100.13                  Snow  
8780               24              9.7           100.03                  Snow  
8781               28              4.8            99.95                  Snow  
8782               28              9.7            99.91                  Snow  
8783               30             11.3            99.89                  Snow  

[8784 rows x 8 columns]

In [8]:
weather_df["Weather"].head()

0                     Fog
1                     Fog
2    Freezing Drizzle,Fog
3    Freezing Drizzle,Fog
4                     Fog
Name: Weather, dtype: object

In [7]:
weather_df[["Weather", "Dew Point Temp (C)"]].head()

Weather  Dew Point Temp (C)
0                   Fog                -3.9
1                   Fog                -3.7
2  Freezing Drizzle,Fog                -3.4
3  Freezing Drizzle,Fog                -3.2
4                   Fog                -3.3

In [9]:
weather_df[:25]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0   2012-01-01 00:00:00      -1.8                -3.9           86   
1   2012-01-01 01:00:00      -1.8                -3.7           87   
2   2012-01-01 02:00:00      -1.8                -3.4           89   
3   2012-01-01 03:00:00      -1.5                -3.2           88   
4   2012-01-01 04:00:00      -1.5                -3.3           88   
5   2012-01-01 05:00:00      -1.4                -3.3           87   
6   2012-01-01 06:00:00      -1.5                -3.1           89   
7   2012-01-01 07:00:00      -1.4                -3.6           85   
8   2012-01-01 08:00:00      -1.4                -3.6           85   
9   2012-01-01 09:00:00      -1.3                -3.1           88   
10  2012-01-01 10:00:00      -1.0                -2.3           91   
11  2012-01-01 11:00:00      -0.5                -2.1           89   
12  2012-01-01 12:00:00      -0.2                -2.0           88   
13  2012-01-01 13:00:00       0.2                -1.7           87   
14  2012-01-01 14:00:00       0.8                -1.1           87   
15  2012-01-01 15:00:00       1.8                -0.4           85   
16  2012-01-01 16:00:00       2.6                -0.2           82   
17  2012-01-01 17:00:00       3.0                 0.0           81   
18  2012-01-01 18:00:00       3.8                 1.0           82   
19  2012-01-01 19:00:00       3.1                 1.3           88   
20  2012-01-01 20:00:00       3.2                 1.3           87   
21  2012-01-01 21:00:00       4.0                 1.7           85   
22  2012-01-01 22:00:00       4.4                 1.9           84   
23  2012-01-01 23:00:00       5.3                 2.0           79   
24  2012-01-02 00:00:00       5.2                 1.5           77   

    Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                 4              8.0           101.24                   Fog  
1                 4              8.0           101.24                   Fog  
2                 7              4.0           101.26  Freezing Drizzle,Fog  
3                 6              4.0           101.27  Freezing Drizzle,Fog  
4                 7              4.8           101.23                   Fog  
5                 9              6.4           101.27                   Fog  
6                 7              6.4           101.29                   Fog  
7                 7              8.0           101.26                   Fog  
8                 9              8.0           101.23                   Fog  
9                15              4.0           101.20                   Fog  
10                9              1.2           101.15                   Fog  
11                7              4.0           100.98                   Fog  
12                9              4.8           100.79                   Fog  
13               13              4.8           100.58                   Fog  
14               20              4.8           100.31                   Fog  
15               22              6.4           100.07                   Fog  
16               13             12.9            99.93         Mostly Cloudy  
17               13             16.1            99.81                Cloudy  
18               15             12.9            99.74                  Rain  
19               15             12.9            99.68                  Rain  
20               19             25.0            99.50                Cloudy  
21               20             25.0            99.39                Cloudy  
22               24             19.3            99.32          Rain Showers  
23               30             25.0            99.31                Cloudy  
24               35             25.0            99.26          Rain Showers

In [11]:
weather_df[:9:2][["Weather", "Visibility (km)", "Rel Hum (%)"]]

Weather  Visibility (km)  Rel Hum (%)
0                   Fog              8.0           86
2  Freezing Drizzle,Fog              4.0           89
4                   Fog              4.8           88
6                   Fog              6.4           89
8                   Fog              8.0           85

Avoid slicing on DF

In [17]:
# .loc and .iloc

weather_df[["Visibility (km)", "Rel Hum (%)", "Temp (C)"]].loc[10:25] # loc uses location

Visibility (km)  Rel Hum (%)  Temp (C)
10              1.2           91      -1.0
11              4.0           89      -0.5
12              4.8           88      -0.2
13              4.8           87       0.2
14              4.8           87       0.8
15              6.4           85       1.8
16             12.9           82       2.6
17             16.1           81       3.0
18             12.9           82       3.8
19             12.9           88       3.1
20             25.0           87       3.2
21             25.0           85       4.0
22             19.3           84       4.4
23             25.0           79       5.3
24             25.0           77       5.2
25             25.0           72       4.6

In [15]:
weather_df[["Visibility (km)", "Rel Hum (%)", "Temp (C)"]].iloc[10:25] # iloc uses index of the location

Visibility (km)  Rel Hum (%)  Temp (C)
10              1.2           91      -1.0
11              4.0           89      -0.5
12              4.8           88      -0.2
13              4.8           87       0.2
14              4.8           87       0.8
15              6.4           85       1.8
16             12.9           82       2.6
17             16.1           81       3.0
18             12.9           82       3.8
19             12.9           88       3.1
20             25.0           87       3.2
21             25.0           85       4.0
22             19.3           84       4.4
23             25.0           79       5.3
24             25.0           77       5.2

In [19]:
# filtering
# find every instance where there was snow

weather_df["Weather"].unique()

array(['Fog', 'Freezing Drizzle,Fog', 'Mostly Cloudy', 'Cloudy', 'Rain',
       'Rain Showers', 'Mainly Clear', 'Snow Showers', 'Snow', 'Clear',
       'Freezing Rain,Fog', 'Freezing Rain', 'Freezing Drizzle',
       'Rain,Snow', 'Moderate Snow', 'Freezing Drizzle,Snow',
       'Freezing Rain,Snow Grains', 'Snow,Blowing Snow', 'Freezing Fog',
       'Haze', 'Rain,Fog', 'Drizzle,Fog', 'Drizzle',
       'Freezing Drizzle,Haze', 'Freezing Rain,Haze', 'Snow,Haze',
       'Snow,Fog', 'Snow,Ice Pellets', 'Rain,Haze', 'Thunderstorms,Rain',
       'Thunderstorms,Rain Showers', 'Thunderstorms,Heavy Rain Showers',
       'Thunderstorms,Rain Showers,Fog', 'Thunderstorms',
       'Thunderstorms,Rain,Fog',
       'Thunderstorms,Moderate Rain Showers,Fog', 'Rain Showers,Fog',
       'Rain Showers,Snow Showers', 'Snow Pellets', 'Rain,Snow,Fog',
       'Moderate Rain,Fog', 'Freezing Rain,Ice Pellets,Fog',
       'Drizzle,Ice Pellets,Fog', 'Drizzle,Snow', 'Rain,Ice Pellets',
       'Drizzle,Snow,Fog', 

In [26]:
snow_filter = weather_df["Weather"].str.lower().str.contains("snow")

In [28]:
weather_df[snow_filter]

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
41    2012-01-02 17:00:00      -2.1                -9.5           57   
44    2012-01-02 20:00:00      -5.6               -13.4           54   
45    2012-01-02 21:00:00      -5.8               -12.8           58   
47    2012-01-02 23:00:00      -7.4               -14.1           59   
48    2012-01-03 00:00:00      -9.0               -16.0           57   
...                   ...       ...                 ...          ...   
8779  2012-12-31 19:00:00       0.1                -2.7           81   
8780  2012-12-31 20:00:00       0.2                -2.4           83   
8781  2012-12-31 21:00:00      -0.5                -1.5           93   
8782  2012-12-31 22:00:00      -0.2                -1.8           89   
8783  2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)       Weather  
41                 22             25.0            99.66  Snow Showers  
44                 24             25.0           100.07  Snow Showers  
45                 26             25.0           100.15  Snow Showers  
47                 17             19.3           100.27  Snow Showers  
48                 28             25.0           100.35  Snow Showers  
...               ...              ...              ...           ...  
8779               30              9.7           100.13          Snow  
8780               24              9.7           100.03          Snow  
8781               28              4.8            99.95          Snow  
8782               28              9.7            99.91          Snow  
8783               30             11.3            99.89          Snow  

[583 rows x 8 columns]

In [32]:
wind_filter = weather_df[(weather_df["Wind Spd (km/h)"] > 24) & (weather_df["Visibility (km)"] == 25)]

In [33]:
wind_filter

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
23    2012-01-01 23:00:00       5.3                 2.0           79   
24    2012-01-02 00:00:00       5.2                 1.5           77   
25    2012-01-02 01:00:00       4.6                 0.0           72   
26    2012-01-02 02:00:00       3.9                -0.9           71   
27    2012-01-02 03:00:00       3.7                -1.5           69   
...                   ...       ...                 ...          ...   
8705  2012-12-28 17:00:00      -8.6               -12.0           76   
8753  2012-12-30 17:00:00     -12.1               -15.8           74   
8755  2012-12-30 19:00:00     -13.4               -16.5           77   
8759  2012-12-30 23:00:00     -12.1               -15.1           78   
8760  2012-12-31 00:00:00     -11.1               -14.4           77   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)        Weather  
23                 30             25.0            99.31         Cloudy  
24                 35             25.0            99.26   Rain Showers  
25                 39             25.0            99.26         Cloudy  
26                 32             25.0            99.26  Mostly Cloudy  
27                 33             25.0            99.30  Mostly Cloudy  
...               ...              ...              ...            ...  
8705               26             25.0           101.34   Mainly Clear  
8753               28             25.0           101.26   Mainly Clear  
8755               26             25.0           101.47   Mainly Clear  
8759               28             25.0           101.52  Mostly Cloudy  
8760               26             25.0           101.51         Cloudy  

[308 rows x 8 columns]

In [112]:
weather_df["Weather"].iloc[80]

'Mostly Cloudy'

In [113]:
# working with columns and operations

add_10 = weather_df["Wind Spd (km/h)"] + 10

In [115]:
add_10.head()

0    14
1    14
2    17
3    16
4    17
Name: Wind Spd (km/h), dtype: int64

In [119]:
def multiply(val):
    return val * 3

weather_df_multiplied = weather_df["Wind Spd (km/h)"].apply(multiply)

In [120]:
weather_df_multiplied

0       12
1       12
2       21
3       18
4       21
        ..
8779    90
8780    72
8781    84
8782    84
8783    90
Name: Wind Spd (km/h), Length: 8784, dtype: int64

In [121]:
weather_df["Visibility in meters (m)"] = weather_df["Visibility (km)"] * 1000

In [122]:
weather_df.head()

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  \
0                4              8.0           101.24                   Fog   
1                4              8.0           101.24                   Fog   
2                7              4.0           101.26  Freezing Drizzle,Fog   
3                6              4.0           101.27  Freezing Drizzle,Fog   
4                7              4.8           101.23                   Fog   

   Visibility in meters (m)  
0                    8000.0  
1                    8000.0  
2                    4000.0  
3                    4000.0  
4                    4800.0

In [123]:
weather_df.rename(columns = {"Visibility in meters (m)" : "Visibility (m)"}, inplace = True)

In [124]:
weather_df.head(5)

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0 2012-01-01 00:00:00      -1.8                -3.9           86   
1 2012-01-01 01:00:00      -1.8                -3.7           87   
2 2012-01-01 02:00:00      -1.8                -3.4           89   
3 2012-01-01 03:00:00      -1.5                -3.2           88   
4 2012-01-01 04:00:00      -1.5                -3.3           88   

   Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  \
0                4              8.0           101.24                   Fog   
1                4              8.0           101.24                   Fog   
2                7              4.0           101.26  Freezing Drizzle,Fog   
3                6              4.0           101.27  Freezing Drizzle,Fog   
4                7              4.8           101.23                   Fog   

   Visibility (m)  
0          8000.0  
1          8000.0  
2          4000.0  
3          4000.0  
4          4800.0

In [126]:
weather_df.drop(labels=["Visibility (m)"], axis=1) # axis=0 is x axis, 1 is y axis

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
0    2012-01-01 00:00:00      -1.8                -3.9           86   
1    2012-01-01 01:00:00      -1.8                -3.7           87   
2    2012-01-01 02:00:00      -1.8                -3.4           89   
3    2012-01-01 03:00:00      -1.5                -3.2           88   
4    2012-01-01 04:00:00      -1.5                -3.3           88   
...                  ...       ...                 ...          ...   
8779 2012-12-31 19:00:00       0.1                -2.7           81   
8780 2012-12-31 20:00:00       0.2                -2.4           83   
8781 2012-12-31 21:00:00      -0.5                -1.5           93   
8782 2012-12-31 22:00:00      -0.2                -1.8           89   
8783 2012-12-31 23:00:00       0.0                -2.1           86   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)               Weather  
0                   4              8.0           101.24                   Fog  
1                   4              8.0           101.24                   Fog  
2                   7              4.0           101.26  Freezing Drizzle,Fog  
3                   6              4.0           101.27  Freezing Drizzle,Fog  
4                   7              4.8           101.23                   Fog  
...               ...              ...              ...                   ...  
8779               30              9.7           100.13                  Snow  
8780               24              9.7           100.03                  Snow  
8781               28              4.8            99.95                  Snow  
8782               28              9.7            99.91                  Snow  
8783               30             11.3            99.89                  Snow  

[8784 rows x 8 columns]

In [127]:
weather_df.sort_values("Temp (C)", ascending=True)

Date/Time  Temp (C)  Dew Point Temp (C)  Rel Hum (%)  \
344  2012-01-15 08:00:00     -23.3               -28.5           62   
342  2012-01-15 06:00:00     -23.2               -28.5           62   
343  2012-01-15 07:00:00     -22.8               -28.0           62   
345  2012-01-15 09:00:00     -22.2               -27.8           60   
338  2012-01-15 02:00:00     -21.4               -26.6           63   
...                  ...       ...                 ...          ...   
4694 2012-07-14 14:00:00      32.7                15.3           35   
5199 2012-08-04 15:00:00      32.8                18.8           44   
4696 2012-07-14 16:00:00      32.9                15.3           35   
4143 2012-06-21 15:00:00      33.0                19.0           44   
4695 2012-07-14 15:00:00      33.0                16.8           38   

      Wind Spd (km/h)  Visibility (km)  Stn Press (kPa)        Weather  \
344                 7             24.1           102.45          Clear   
342                 7             25.0           102.28  Mostly Cloudy   
343                 9             25.0           102.37   Mainly Clear   
345                 9             48.3           102.57   Mainly Clear   
338                 9             25.0           101.99         Cloudy   
...               ...              ...              ...            ...   
4694               28             48.3           101.35   Mainly Clear   
5199               17             24.1           101.39          Clear   
4696               24             48.3           101.26   Mainly Clear   
4143               24             24.1           100.20   Mainly Clear   
4695               22             48.3           101.31   Mainly Clear   

      Visibility (m)  
344          24100.0  
342          25000.0  
343          25000.0  
345          48300.0  
338          25000.0  
...              ...  
4694         48300.0  
5199         24100.0  
4696         48300.0  
4143         24100.0  
4695         48300.0  

[8784 rows x 9 columns]

In [133]:
weather_df.sort_values("Temp (C)", ascending=False)["Temp (C)"].value_counts().head(10)

Temp (C)
16.6    65
1.1     58
0.8     47
1.5     45
19.3    44
21.1    43
2.6     43
0.4     41
1.3     40
14.6    39
Name: count, dtype: int64

In [135]:
sorted_temp_vals = weather_df.sort_values("Temp (C)", ascending=False)["Temp (C)"].value_counts()
sorted_temp_vals.iloc[:10]

Temp (C)
16.6    65
1.1     58
0.8     47
1.5     45
19.3    44
21.1    43
2.6     43
0.4     41
1.3     40
14.6    39
Name: count, dtype: int64

In [136]:
weather_df["Temp (C)"].mean()

8.798144353369764

In [144]:
# mean temp recorded by month

mean_temp_by_month = {}

for month in range(1, 13):
    mean_temp_by_month[month] = weather_df.loc[weather_df["Date/Time"].dt.month == month, "Temp (C)"].mean()

pd.Series(mean_temp_by_month)

1     -7.371505
2     -4.225000
3      3.121237
4      7.009306
5     16.237769
6     20.134028
7     22.790054
8     22.279301
9     16.484444
10    10.954973
11     0.931389
12    -3.306317
dtype: float64

In [145]:
mean_temp_by_month

{1: -7.371505376344086,
 2: -4.225,
 3: 3.1212365591397857,
 4: 7.009305555555557,
 5: 16.2377688172043,
 6: 20.134027777777778,
 7: 22.790053763440863,
 8: 22.279301075268815,
 9: 16.484444444444442,
 10: 10.954973118279572,
 11: 0.9313888888888887,
 12: -3.3063172043010756}

In [158]:
 # pivot tables

data = {
    "A": ["foo", "bar", "bar", "foo", "foo", "bar"],
    "B": ["one", "one", "two", "two", "one", "two"],
    "C": ["x", "y", "z", "y", "z", "x"],
    "D": [1, 2, 3, 4, 5, 6]
}

df = pd.DataFrame(data)
df

A    B  C  D
0  foo  one  x  1
1  bar  one  y  2
2  bar  two  z  3
3  foo  two  y  4
4  foo  one  z  5
5  bar  two  x  6

In [159]:
pivot_df = df.pivot_table(
    values="D",
    index="A",
    columns=["C"],
    aggfunc="sum"
)

pivot_df

C    x  y  z
A           
bar  6  2  3
foo  1  4  5

In [160]:
pivot_df.reset_index()

C    A  x  y  z
0  bar  6  2  3
1  foo  1  4  5

In [162]:
weather_df[["Temp (C)", "Date/Time"]]

Temp (C)           Date/Time
0         -1.8 2012-01-01 00:00:00
1         -1.8 2012-01-01 01:00:00
2         -1.8 2012-01-01 02:00:00
3         -1.5 2012-01-01 03:00:00
4         -1.5 2012-01-01 04:00:00
...        ...                 ...
8779       0.1 2012-12-31 19:00:00
8780       0.2 2012-12-31 20:00:00
8781      -0.5 2012-12-31 21:00:00
8782      -0.2 2012-12-31 22:00:00
8783       0.0 2012-12-31 23:00:00

[8784 rows x 2 columns]

In [164]:
weather_by_month = weather_df.pivot_table(values="Temp (C)", index=weather_df["Date/Time"].dt.month, aggfunc="mean")

In [165]:
weather_by_month

Temp (C)
Date/Time           
1          -7.371505
2          -4.225000
3           3.121237
4           7.009306
5          16.237769
6          20.134028
7          22.790054
8          22.279301
9          16.484444
10         10.954973
11          0.931389
12         -3.306317

In [174]:
# Groupby

mean_temp = weather_df.groupby(weather_df["Date/Time"].dt.month).mean(numeric_only=True)

In [175]:
mean_temp

Temp (C)  Dew Point Temp (C)  Rel Hum (%)  Wind Spd (km/h)  \
Date/Time                                                                
1          -7.371505          -12.294758    68.383065        18.108871   
2          -4.225000           -9.221695    68.956897        14.837644   
3           3.121237           -3.488575    64.862903        14.514785   
4           7.009306           -1.934583    56.150000        17.369444   
5          16.237769            8.080780    61.760753        12.846774   
6          20.134028           11.738056    60.643056        14.681944   
7          22.790054           14.595430    62.017473        11.887097   
8          22.279301           15.644758    67.943548        13.931452   
9          16.484444           10.757917    71.165278        14.108333   
10         10.954973            6.533468    75.731183        15.475806   
11          0.931389           -4.179306    69.984722        13.973611   
12         -3.306317           -6.129032    81.299731        17.614247   

           Visibility (km)  Stn Press (kPa)  Visibility (m)  
Date/Time                                                    
1                22.100269       101.005349    22100.268817  
2                25.182184       101.142414    25182.183908  
3                26.177957       101.335255    26177.956989  
4                31.777083       100.716833    31777.083333  
5                29.418548       101.057164    29418.548387  
6                32.104167       100.784222    32104.166667  
7                33.655108       100.828333    33655.107527  
8                30.192608       100.927097    30192.607527  
9                30.603472       101.087903    30603.472222  
10               25.111022       100.909368    25111.021505  
11               26.077083       101.658306    26077.083333  
12               19.733199       101.174409    19733.198925